name: Variable Testing

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Variables
      run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git#$GITHUB_REF
