name: Variable Testing

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest
    
    steps:
    # extract branch name
    - name: Extract branch name
      shell: bash
      run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      id: extract_branch
    - name: Variables
      run: echo ${{ github.server_url }}/${{ github.repository }}.git#${{ env.branch_name }}
